services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 --timeout=30 -- poetry run alembic upgrade head &&
            poetry run uvicorn messagingservice.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: